name: Build
on:
  push:
      branches: [main]
        workflow_dispatch:
        jobs:
          buildWindows:
              runs-on: windows-latest
                  steps:
                        - uses: actions/checkout@v4
                              - uses: krdlab/setup-haxe@master
                                      with:
                                                haxe-version: 4.3.4
                                                      - name: Install Haxelib
                                                              run: setup\setup-windows.bat
                                                                      shell: cmd
                                                                            - name: Compile
                                                                                    run: haxelib run lime build windows
                                                                                          - name: Publish Artifact
                                                                                                  uses: actions/upload-artifact@v4
                                                                                                          with:
                                                                                                                    name: windowsBuild
                                                                                                                              path: export/release/windows/bin
                                                                                                                              
